export const NOTIFICATION_PAGE_DEFAULT_LIMIT = 20;
export const NOTIFICATION_PAGE_MAX_LIMIT = 30;

export const PRODUCT_EXPIRY_NOTICE_DAYS_MIN = 1;
export const PRODUCT_EXPIRY_NOTICE_DAYS_MAX = 90;
export const PRODUCT_EXPIRY_NOTICE_DAYS_DEFAULT = 14;
export const PRODUCT_EXPIRY_SWEEP_BATCH_SIZE = 500;
