export const NOTIFICATION_PAGE_DEFAULT_LIMIT = 20;
export const NOTIFICATION_PAGE_MAX_LIMIT = 30;
export const NOTIFICATION_READ_RETENTION_DAYS = 90;
export const NOTIFICATION_SAFETY_READ_RETENTION_DAYS = 365;
export const NOTIFICATION_RETENTION_SWEEP_INTERVAL_MS = 6 * 60 * 60 * 1000;

export const PRODUCT_EXPIRY_NOTICE_DAYS_MIN = 1;
export const PRODUCT_EXPIRY_NOTICE_DAYS_MAX = 90;
export const PRODUCT_EXPIRY_NOTICE_DAYS_DEFAULT = 14;
export const PRODUCT_EXPIRY_SWEEP_BATCH_SIZE = 500;
